Firebase연동: Home, GroupDetail
WIT-Projects/RTiccle-App pull request #18
Opened 2021-12-23 08:31 UTC by Hongji0611

## 개요
- Home과 GroupDetail을  Firebase와 연동

## 상세내용
**Home: 신규 티끌이 생성된 그룹**
- 생성된 그룹을 10개 보여줍니다. 
- 포함되어있는 티끌 개수도 확인할 수 있습니다. 
- 그룹을 선택하면 해당 그룹의 상세화면으로 전환됩니다.

**GroupDetail**
- 그룹의 제목, 설명, 이미지를 가져옵니다.
- 해당 그룹에 티끌이 존재하는 경우과 없는 경우를 나누었습니다.
- 티끌이 존재하는 경우 해당 티끌의 제목과 태그를 보여줍니다.

## 리뷰어가 확인할 사항
- Home에서 즐겨찾기는 그룹 수정이 가능해진 다음에 구현할 예정입니다.
- Home에서 신규 티끌에 해당하는 그룹을 가져오기가 까다로워 좀 더 고민해보려고 합니다.. 아이디어가 있으시다면 알려주세요...!   
(현재는 모든 그룹을 가져오는 방식으로 구현했습니다.)

## 기타
- Home에서 어떤 티끌도 존재하지 않는 경우에 대한 화면이 필요합니다.
- 모든 그룹을 확인할 수 있는 화면이 디자인 상에서 없는 것으로 보입니다. 논의가 필요합니다!

2021-12-23 11:10 UTC, 0JIEUN0 requested changes
수고하셨습니다!
이하 comment 를 바탕으로 의견 주시면 감사하겠습니다.

+) PR 내용에 '신규 티끌에 해당하는 그룹' 의 경우, 신규 티끌이 작성되면 그 그룹의 lastModifiedTime 을 업데이트할 예정입니다. 아직 구현되지는 않았지만, 그렇게 하면 신규 티끌이 있는 그룹 순으로 가져올 수 있을 것입니다.

2021-12-23 11:10 UTC, 0JIEUN0 commented on src/containers/group/detail/container/GroupDetailContainer.js
> +async function getGroupDataIncludeImage(groupId) {
이렇게 데이터를 가공하거나 주고받는 기능은 다 Firebase 폴더 내에서 하려고 구조를 짜고 작업했습니다.
즉, 이 함수는 데이터를 주고받는 기능을 하는 함수이니 지금처럼 여기에 종속되는 형태가 아니라, firebase 와의 작업을 수행하는 부분 (지금의 firestore.js) 에 있는 것이 적합하다고 생각합니다. ('화면'에서는 데이터 작업이 이루어지지 않고, '어딘가에서(지금은 firestore.js)' 필요한 데이터를 받는 구조)

+) 이렇게 추가로 필요한 함수는 직접 firestore.js 나 기타 파일을 수정해주시거나 제게 요청하시면 작업하도록 하겠습니다.

2021-12-23 11:10 UTC, 0JIEUN0 commented on src/containers/group/detail/index.js
> +import { getGroupDataIncludeImage, getTiccleList } from './container/GroupDetailContainer';
그래서 제가 제안드리는 것은, 지금처럼 이 두 함수를 끌어다 사용하는 것이 아니라, 이 컴포넌트 내에서 바로 firestore.js 에 있는 함수를 사용하자는 것입니다.
 이렇게 각 요소(그룹 생성, 수정 등의 프로세스)마다 커스텀 함수를 사용한다면 firebase 와 작업하는 부분을 분리한 효과가 없어지며, 중복된 함수들이 증가하며 추후 유지보수가 어려울 수 있기 때문입니다.

2021-12-23 11:10 UTC, 0JIEUN0 commented on src/containers/home/container/HomeContainer.js
> +    const groupList = await findGroupsIncludeImage(size);
혹시 이 경우 findGroupsIncludeImage 함수 결과물을 바로 반환하는 동작을 수행하는 함수가 되는데, 따로 분리해서 작성하신 이유가 무엇인가요?? 저는 필요한 컴포넌트에서 findGroupsIncludeImage 등을 바로 사용하는 형태를 생각했었습니다. 서로 다른 구조를 생각한 것 같아서 여쭤봅니다!

2021-12-23 13:08 UTC, Hongji0611 commented on src/containers/group/detail/container/GroupDetailContainer.js
> +async function getGroupDataIncludeImage(groupId) {
그러면 firestore.js를 노션에 명시해둔 것처럼 sserFirestore, groupFirestore, ticcleFirestore로 구분하는건 어떠실까요?

2021-12-23 13:15 UTC, 0JIEUN0 commented on src/containers/group/detail/container/GroupDetailContainer.js
> +async function getGroupDataIncludeImage(groupId) {
그것도 좋은 것 같아요! 애초에 Firestore.js 라는 네이밍도 바꾸려 했으니 다음 작업 시 반영해서 올리도록 할게요!

2021-12-23 16:41 UTC, Hongji0611 commented on src/containers/group/detail/container/GroupDetailContainer.js
> +async function getGroupDataIncludeImage(groupId) {
container 폴더 삭제 후 필요한 함수들을 Firestore.js에 추가했습니다! (아래 코멘트들도 반영했습니다)

2021-12-23 17:34 UTC, bella0413 approved these changes
`src/containers/group/detail/index.js`
 `src/containers/home/index.js`
파일명을 index.js가 아닌 명시성 있는 이름으로 하기로 했었는데, 그것만 반영 부탁드립니다!
수고하셨어요👍👍

2021-12-27 08:43 UTC, never-better commented on src/containers/home/container/HomeContainer.js
> +    const groupList = await findGroupsIncludeImage(size);
저도 따로 작성하신 이유가 궁금합니다

2021-12-27 08:43 UTC, never-better commented on src/containers/home/components/TiccleGroup.js
> +                        style={{ width: "100%", height: 140 }}>
스타일 나눠 주세요

2021-12-27 08:43 UTC, never-better commented on src/containers/home/components/TiccleGroup.js
> +                            <View style={{alignItems: 'flex-end', marginRight: 18, marginVertical: 25}}>
스타일 나눠 주세요2

2021-12-27 10:51 UTC, Hongji0611 commented on src/containers/home/components/TiccleGroup.js
> +                            <View style={{alignItems: 'flex-end', marginRight: 18, marginVertical: 25}}>
둘 다 반영했습니다

2021-12-27 11:23 UTC, 0JIEUN0 approved these changes

2021-12-27 11:23 UTC, merged