Ticcle create with image picker
WIT-Projects/RTiccle-App pull request #19
Opened 2021-12-26 07:36 UTC by never-better

## 개요
티끌 생성 페이지 

## 상세내용
image crop Picker로 실제 이미지 티끌에 추가합니다.
@bella0413 님이 구현하신 photoModal 창 style 조금 수정했습니다.
티끌 상세화면에서 이미지 클릭시 이미지 상세화면이 나타납니다.
customModal 창 구현했습니다. 사용법 노션에 작성했습니다.
https://www.notion.so/wit202103/customModal-0c15c395c5a746af95e5512ddadb25d8

## 리뷰어가 확인할 사항
랜덤 id 생성을 위해 uuid & get-random-values 패키지 설치했습니다.

티끌을 다 작성하고 저장 버튼을 누르면 ticcleCreate 라는 state에 ticcle의 정보가 모두 저장됩니다.

![image](https://user-images.githubusercontent.com/71776532/147401670-fe454518-e2c7-45dd-b8fa-626c6b1c5ee2.png)
useTiccleCreate() 라는 Custom useContext를 통해 앱 어디서든 ticcle을 불러와 사용할 수 있습니다.

![image](https://user-images.githubusercontent.com/71776532/147401695-2161afcf-aec1-4994-b452-ac995f587d3e.png)
티끌 구조

## 기타
태그 디자인이 수정된 것 같아서 우선은 태그 기능은 남겨두었습니다.

현재 ticcleCreate 라는 state에 티끌 정보가 저장되어있는데 ticcleCurrent라는 읽기 전용 state를 하나 더 만들어서 관리할까 합니다.
티끌 state 를 하나만 사용할 경우 티끌 상세 페이지 화면에서 의도치 않게 티끌이 수정될 가능성이 있어, 사전에 예방하기 위해서 읽기 전용이 필요할 것 같은데 의견 부탁드립니다.

![image](https://user-images.githubusercontent.com/71776532/147401811-77843b5c-5118-4be3-8d1d-bfbc455bf46c.png)

2021-12-26 15:38 UTC, bella0413 commented on src/containers/common/PhotoModal.js
> +                <TouchableOpacity style={styles.textConatiner} onPress={takePhotoFromCamera}>
https://github.com/react-native-modal/react-native-modal
저희가 사용한 라이브러리 예제를 보시면 아시겠지만 굳이 TouchableOpacity로 감쌀 필요가 없습니다.
원래 형식대로 가되 css를 수정하는 게 코드도 더 간결하고 좋을 것 같아요.
TouchableOpacity와 style의 textConatiner를 포함시키지 않더라도 충분히 수정 가능한 css라고 생각합니다!

2021-12-26 15:40 UTC, bella0413 commented on src/containers/common/PhotoModal.js
> -        alignItems: 'flex-start',
위에서 했던 이야기를 이어서 하자면 여기서 `padding: 30`을 빼고
`paddingVertical: 28, paddingHorizontal: 23` 을 넣으면 디자인대로 수정이 됩니다.
그럼 textContainer를 굳이 넣을 필요가 없어요. 
제가 웹이랑 헷갈려서 이상하게 코드를 작성했네요...ㅠㅠ 알아차려주셔서 감사합니다!

2021-12-26 15:52 UTC, bella0413 commented on src/containers/ticcle/create/components/TiccleImage.js
> +import { TouchableOpacity,Image, StyleSheet, View, Alert } from 'react-native';
Alert 는 사용되지 않는 것 같습니다. 사용되지 않는 친구는 제외해주세요!

2021-12-26 15:57 UTC, bella0413 commented on src/containers/ticcle/create/components/TiccleImageGroup.js
> +            <TiccleImage key={imageSource.id} setPhotoModalVisibleTrue={photoModalVisibleTrue}
21번째 라인과 동일하게 `{photoModalVisibleTrue}`를 props로 전달하고 있는데 이름이 비슷하면서 다릅니다.
함수로 감싸서 전달하신다면 props의 이름을 통일하는 게 헷갈리지 않을 것 같아요.

2021-12-26 16:00 UTC, bella0413 commented on src/containers/ticcle/create/index.js
> +const TiccleCreate = () => {
전에 협의했던대로 파일명을 index.js가 아니라  명시성 있는 이름으로 변경 부탁드립니다!

2021-12-26 16:05 UTC, bella0413 commented on src/containers/ticcle/detail/index.js
파일명 변경 부탁드립니다!

2021-12-26 16:06 UTC, bella0413 reviewed
`src/containers/ticcle/create/index.js`
`src/containers/ticcle/detail/index.js`
전에 협의했던대로 파일명을 index.js가 아니라 명시성 있는 이름으로 변경 부탁드립니다!

2021-12-26 16:17 UTC, bella0413 commented on src/context/hook/UseTiccleCreate.js
> +export default useTiccleCreate
파일명이랑 다르게 소문자로 시작합니다. import하실 때 useTiccleCreate와 UseTiccleCreate를 섞어서 사용하셨는데 통일 부탁드려요.

2021-12-27 08:36 UTC, bella0413 commented on src/navigation/stack/TiccleStackNavigator.js
> +                    deleteTiccleCreate()
초기화하는 게 목적인 것 같아서 `deleteTiccleCreate`보다는 `initialTiccleCreate`같은 게 더 어울릴 것 같아요😊

2021-12-27 09:01 UTC, never-better commented on src/containers/common/PhotoModal.js
> +                <TouchableOpacity style={styles.textConatiner} onPress={takePhotoFromCamera}>
버튼 누를 때 누른 느낌이 안 나서 TouchableOpacity로 감싸주었습니다.
확인해보고 더 괜찮은 걸 사용하면 될 것 같습니다.

2021-12-27 10:39 UTC, 0JIEUN0 requested changes

2021-12-27 10:39 UTC, 0JIEUN0 commented on src/containers/ticcle/create/components/TiccleImage.js
> +const TiccleImage = ({setPhotoModalVisibleTrue, deleteImage ,imageSource, imageId}) => {
중복 방지를 위해 이전에 회의한 것처럼 TiccleCreateImage 와 같이 사용하면 좋을 것 같습니다.
이하 다른 컴포넌트에도 적용이 필요해보입니다. (TiccleImageGroup 등)

2021-12-27 11:07 UTC, never-better commented on src/containers/ticcle/create/components/TiccleImage.js
> +const TiccleImage = ({setPhotoModalVisibleTrue, deleteImage ,imageSource, imageId}) => {
적용완료했습니다.

2021-12-27 11:33 UTC, 0JIEUN0 approved these changes

2021-12-27 11:38 UTC, Hongji0611 approved these changes

2021-12-27 11:49 UTC, merged