Feat/group
WIT-Projects/RTiccle-App pull request #26
Opened 2022-01-05 00:08 UTC by bella0413

## 개요
- 그룹 업데이트 기능

## 상세내용
-  MainTab에서 경로에 따라 탭의 존재 유무를 설정해서 `MainStackNavigator`에 알맞지 않은 스크린들은 `HomeStackNavigator`로 이동시켰습니다.
- `groupUpdate`를 useContext로 관리합니다. 
- update시 초기값과 변경된 값을 비교하여 모달 띄우기, 취소 누르면 원래대로 돌아가기 등 여러 이유가 있어 `initialData`라는 state를 사용했습니다.
- 화면 렌더링에 필요한 값이 비면 에러가 나서 `useEffect`를 두 번 사용하여 해결했습니다. (ex. `groupUpdate`를 서버로부터 받아온 값으로 set하는 것이 데이터를 받기 전에 일어남.) 이렇게 하면 `useEffect`가 처음 화면이 렌더링될 때와 필요한 데이터가 들어왔을 때 실행되며 불필요한 렌더링은 없는 것으로 확인했습니다. 저희가 어제 이야기했던 부분이랑 조금 겹치는 부분인 것 같습니다.
- `groupTitle`과 `groupDescription`을 업데이트하기 위해 버튼을 누르면 모달이 전체 화면 크기로 뜹니다. 모달이 뜨면 뒤에 사라지는 영역은 조건부 렌더링 등으로 처리했습니다.
- `groupUpdate`의 textInput에 글자수 제한 디자인을 넣었고, `title`의 경우 글자수가 0이면 저장 버튼이 `disabled`되도록 설정하였습니다. 그룹 중복은 아직 디자인이 나오지 않았기 때문에 디자인이 나오면 추후에 수정하겠습니다. (group create 쪽 수정사안이랑 함께 이번 주에 PR하겠습니다.)
- 북마크가 useState()로 초기화를 하도록 되어있어서 북마크 후 다시 화면에 들어오면 이미지가 여전히 변경되지 않은 상태였습니다. 그것도 수정할 겸 서버와 비슷하게 `isBookmark`를  boolan값으로 변경했습니다. 하지만 배열로 접근하는 코드 너무 신박했어요👍👍
## 리뷰어가 확인할 사항
- 그룹 업데이트가 여러 필드도 되고 하나의 필드도 되고 잘 작동하는데, 딱 하나 그룹의 `title`을 변경하면 에러가 납니다. 아마 id와 title을 같이 사용하고 있어서 나는 에러 같아요.. @0JIEUN0 님 확인 부탁드립니다!
- ` Possible Unhandled Promise Rejection (id: 0):
Error: [storage/object-not-found] No object exists at the desired reference.` 홈화면에서 이런 에러가 나는데 어떻게 해결하면 좋을까요...

## 기타
- 예) 건의사항 등

2022-01-05 01:46 UTC, 0JIEUN0 requested changes
navigation 이 깔끔해져서 좋습니다!

group `id`, `title` 중복 사용이 걱정되긴 했는데 수정 시 문제가 생기는 걸 생각 못했네요.
아예 `title` 만 사용하도록 변경하도록 하겠습니다. 체크 감사드려요!

2022-01-05 01:46 UTC, 0JIEUN0 commented on src/containers/common/PhotoModal.js
> +                setMainImage(image.path);
PhotoModal 은 common 라서 'mainImage' 라는 말은 안 맞는 것 같아요.
setImage 이렇게 하면 어떤가요?

2022-01-05 01:46 UTC, 0JIEUN0 commented on src/containers/group/detail/components/groupInfo.js
> +    }, [groupData]);
오...흥미롭군요

2022-01-05 01:46 UTC, 0JIEUN0 commented on src/containers/group/update/components/GroupUpdateSaveButton.js
> +        const newInfo = {
updateGroupInfo() 함수의 newInfo 는 'new group info **_(changed info only)_**' 라고 명시해뒀습니다.
변경된 정보가 아닌 것이 있어도 상관은 없지만, 불필요한 서버에 쓰는 작업이 늘어나게 됩니다.
바뀐 정보만 넘기면 어떤가요?

2022-01-05 08:36 UTC, bella0413 commented on src/containers/common/PhotoModal.js
> +                setMainImage(image.path);
이 부분을 제가 고민했던 게 수정 전 이미지를 보여줄 때는 source에 imageUrl을 받아서 보여줘야 합니다. 그런데 자신의 사진 정보를 업데이트할 때는 그룹의 imageUrl이 아닌 값이 source에 담겨야  하구요. 이 둘을 동시에 관리할 변수가 필요해서 mainImage, setMainImage라는 친구를 등장시키게 된 것 입니다. setImage는 위쪽에 보시면 따로 존재하고 있습니다. 이 setMainImage는 그룹을 업데이트하는 곳에서만 이미지 관리를 하기 위해 필요합니다. 그렇지만 PhotoModal은 common이기에 동시에 관리할 더 좋은 방법을 찾고 있습니다! imgUrl, mainImage, ImageSource가 섞이니 조금 헷갈리네요.. 아예 groupUpdateImage를 context로 빼서 사용하거나 그냥 imageUrl이라는 이름을 잘 활용해서 다르게 해결해보겠습니다!

2022-01-05 08:45 UTC, bella0413 commented on src/containers/group/update/components/GroupUpdateSaveButton.js
> +        const newInfo = {
group info의 데이터 크기가 작아서 미처 고려하지 못했네요.. 반영해서 다시 올리겠습니다! 감사합니다!

2022-01-05 13:51 UTC, Hongji0611 commented on src/containers/group/update/components/GroupUpdateDescriptionModal.js
> +    if (description != null) var groupDescriptionLength = description.length;
if문 안에 var를 선언하면 해당 실행주기에만 영향을 가질 수 있는 지역변수 아닌가요?

2022-01-05 14:02 UTC, Hongji0611 commented on src/containers/group/update/components/GroupUpdateTitleModal.js
> +    if (title != null) var groupTitleLength = title.length;
이 부분도 마찬가지 의견입니다! if문 밖으로 변수를 빼는것이 좋아보입니다

2022-01-05 14:17 UTC, Hongji0611 reviewed
수고하셨습니다!
북마크 수정된거 너무 깔끔하고 좋습니다. 홈화면에서 에러나는 상황을 좀더 구체적으로 설명해주시면 수정해보겠습니다 (ex- 즐겨찾기리스트가 없을때 나타나요.)

2022-01-05 14:45 UTC, never-better reviewed
Merge Conflict 리뷰하기만 해도 어지러운데 해결하느라 고생많으셨습니다!

2022-01-05 14:45 UTC, never-better commented on src/containers/group/update/components/GroupUpdateDescriptionModal.js
> +                        groupDescriptionLength === maxLength
이 코드면 maxLength에 도달했을 때 바로 빨간색으로 바뀌는 거 아닌가요?
maxLength에서 추가로 입력하려고 했을 때 빨간색으로 변하면서 문구가 뜨는 것으로 알고 있는데, 이렇게 구현하는데 시간이 많이 소요된다면 기획 / 디자인 단계에서 수정이 필요해 보입니다.

2022-01-05 14:45 UTC, never-better commented on src/containers/group/update/components/GroupUpdateTitleModal.js
> +                        disabled={groupTitleLength < 1 ? true : false}
groupTitleLength < 1 이라는 조건문이 반복되는데, 효율과 가독성을 위해 따로 빼서 작성하면 좋을 것 같아요

2022-01-05 14:45 UTC, never-better commented on src/containers/group/update/components/GroupUpdateTitleModal.js
> +                                groupTitleLength < 1
중복

2022-01-05 14:45 UTC, never-better commented on src/containers/group/update/components/GroupUpdateTitleModal.js
>                                  groupTitleLength === maxLength
얘도 여러번 중복되니까 따로 빼서 관리하면 좋을 것 같아요

2022-01-05 15:01 UTC, bella0413 commented on src/containers/group/update/components/GroupUpdateDescriptionModal.js
> +                        groupDescriptionLength === maxLength
엇 저는 maxLength 도달하면 빨간색으로 뜬다고 생각했어요. 피그마 디자인도 그렇고 애초에 maxLength를 넘어가게 구성하지 않아서요..
디자이너님께 여쭤보겠습니다!

2022-01-05 15:23 UTC, bella0413 commented on src/containers/group/update/components/GroupUpdateTitleModal.js
> +                        disabled={groupTitleLength < 1 ? true : false}
감사합니다! 덕분에 코드가 더 깔끔해졌어요ㅎㅎ

2022-01-05 15:26 UTC, bella0413 commented
- 그룹 수정 시 이미지 관리에 대한 이슈는 변수를 적절히 활용하여 해결했고 불필요한 변수 및 함수는 삭제했습니다.
동일하게 업데이트가 잘 되는 것을 확인했습니다.
- 서버에 데이터를 보낼 때 변경된 정보만 보내도록 수정했습니다.
- 그 밖의 피드백들도 반영했습니다. 다들 감사합니다!

2022-01-05 15:30 UTC, bella0413 commented on src/containers/group/update/components/GroupUpdateDescriptionModal.js
> +    if (description != null) var groupDescriptionLength = description.length;
ㅎㅎㅎ어제 너무 졸렸나봐요....감사합니다!

2022-01-05 15:48 UTC, Hongji0611 approved these changes

2022-01-06 07:50 UTC, 0JIEUN0 commented on src/context/provider/AppProvider.js
> +            return {...state, imageUrl: imgPath};
이게 'imageUrl' 는 uri 인데 (from 서버) 여기서 groupUpdateImage 에 넣어주는거는 image 의 source 아닌가요?
그룹 업데이트에만 요게 쓰이니 괜찮을 것 같기는 한데 혹시 혼동하실까봐 말씀드립니다!

2022-01-06 07:57 UTC, bella0413 commented on src/context/provider/AppProvider.js
> +            return {...state, imageUrl: imgPath};
맞습니다! 다들 전역변수를 꺼리시기도 하고 단순히 업데이트에서만 사용하는거라 그냥 변수를 적당히 활용해서 넣었어요. 그래서 말씀하신 것처럼 맞지 않는 부분도 생긴 거예요. 그대로 두면 헷갈릴 수 있으니 주석을 추가할게요!

2022-01-07 13:06 UTC, 0JIEUN0 approved these changes

2022-01-07 13:07 UTC, merged