Login & GroupDetail -> TiccleDetail 갈 때 그룹 설정
WIT-Projects/RTiccle-App pull request #35
Opened 2022-01-21 08:37 UTC by never-better

## 개요
Login 상태 저장
GroupDetail -> TiccleDetail 그룹 설정
가독성을 위한 TiccleCreat, TiccleDetail 코드 수정

## 상세내용
Login상태 저장
    AsyncStorage를 통해 로그인 상태를 저장합니다.
    App 시작 시에 데이터를 불러옵니다. 값이 저장되어 있지 않으면 Login 페이지를 보여줍니다.
    값이 저장되어 있는 경우에는 기존처럼 MainStackNavigator를 보여줍니다.

GroupDetail -> TiccleDetail 그룹 설정
    Home -> TiccleDetail로 갈 때 params로 {screenFrom: 'home'}을 줍니다.
    bottom Tab을 누를 때마다 params가 전달되도록 코드를 작성했습니다. TiccleCreate.js 의 useEffect 안에 있는 코드가 이와 관 
    련된 코드입니다.
    또 MainStack의 TiccleCreate에 initialParams를 설정했습니다. 설정 안 하면 맨 처음 탭을 누를 시 params를 전달하지 않습니 
    다.
    GroupDetail -> TiccleDetail 로 갈 때 params 로 {screenFrom: groupId} 를 줍니다.
    screenFrom이 home이면 아무 것도 설정하지 않습니다.
    그 외에의 경우에는 ticcle.groupId를 전달받은 groupId로 설정해줍니다.
   
티끌작성화면 태그 입력 시 스크롤 이동
    기존에 태그를 입력하고 엔터 버튼을 누르면, 태그가 키보드에 가려져 안 보였습니다. 엔터를 누르면 스크롤이 제일 아래로 이 
    동하도록 코드를 작성했습니다.

티끌 작성과 티끌 수정 페이지 분리
    TiccleCreate에서 전달받는 params에 따라 티끌 작성화면 혹은 티끌 수정화면을 보여주려고 했습니다.
    코드를 작성하다보니 두 화면에서 로직이 달라 코드가 너무 복잡해졌습니다. 그래서 분리해서 작성하려고 합니다.
    updateMode를 작성했다 지웠는데 이 땜에 그렇습니다 ㅎㅎ

## 리뷰어가 확인할 사항
AsyncStorage 패키지 설치했습니다. 확인해주세요

## 기타
현재 TiccleCreate에서 저장을 하고 TiccleDetail로 넘어가면 몇 가지 오류가 있습니다.
우선은 서버에 저장할 때, Ticcle의 lastModfiedTime이랑 TiccleId가 저장되는데 이를 리턴해주는 함수가 없습니다.
이 때문에 TiccleDetail에서 날짜가 보이지 않습니다.
또 티끌을 생성 하자마자 TiccleDetail 에서 바로 삭제를 하거나 수정을 하려고 하면 ticcleId가 없기 때문에 불가능합니다.

티끌을 수정하려고 할 때 Image Name과 URL을 동시에 다뤄야 하는데 어떻게 할지 고민입니다.
수정할 때 이미지가 보여야 하기 때문에, View에는 imageURL (www.firebase.com/어쩌구저쩌구) 을 뿌려주어야 합니다.
근데 서버에 저장할 때는 imageName(134142321.jpg) 으로 저장해야 합니다.
동시에 두 개의 이미지 배열을 다뤄야 하는데 여기서 너무 복잡해지네요.
(이걸로 이틀을 고민했는데 머리가 터질 것 같아요....)
어떤 식으로 코드를 짜면 좋을지 조언해주시면 감사하겠습니다!
![ticcleEdit](https://user-images.githubusercontent.com/71776532/150493824-e53d2fcb-b918-4ec9-8acf-2cb7b3d4de64.png)

그리고 doUpdateTiccle 함수에서 인자로 넣는 newInfo는 changedOnly 라고 적혀있는데, 수정된 티끌을 전체가 아니라 수정된 부분만 체크해서 인자로 넣는 건가요?? @0JIEUN0 

이번 PR 작성에 사용된 대략적인 DataFlow 입니다.
![ticcleDataFlow](https://user-images.githubusercontent.com/71776532/150494170-be75bb75-0c86-4ee3-8d55-f7170e339ceb.png)
잘 안 보이시면 피그마에서 보시면 됩니다.

2022-01-21 13:23 UTC, 0JIEUN0 requested changes
- 전반적으로 ticcleCreate 를 사용해서 ticcle 정보를 보여주는 화면을 작성해주셨는데, ticcle 에 대한 정보를 props 나 ticcle model 에서 받아서 처리하고 ticcleCreate 는 말그대로 티끌을 작성할 때만 사용하는 것이 어떤가요?

- 티끌에서, `images` 는 이미지 이름들에 대한 배열이고, `imageUrl` 은 해당 이미지들에 대한 downloadUrl 로 구성된 배열입니다. 착오 없으시길 바랍니다. 그리고 티끌 수정은 티끌 정보에서 수정하는 화면으로 이동했을 테니 이미 imageUrl 에 대한 정보 (ticcle 에 대한 정보) 를 갖고 있는 것이 아닌가요? 화면은 서버에 '저장할 이미지'의 '이름'은 신경쓸 필요가 없습니다. 다만, 이미지 수정이 있으면 해당 내용을 서버를 통해 업데이트해주면 됩니다. `imgaeUrl` 은 딱 화면에 보여주는 용도로만 사용하시고 수정할 때는 이미지가 바뀐 것의 여부만 고려하셔서 삭제 후 추가로 업데이트하면 되지 않을까 생각합니다.

- 물어보신 사항(: `doUpdateTiccle` 함수는 변경사항만! 인지) 은 맞습니다. 서버에 write 하는 작업을 줄이기 위해서입니다. 그렇지 않아도 작동은 하지만, 그만큼 많은 내용을 쓰게 되겠죠. group 에서도 같은 방식이니 해당 코드를 참고하시면 될 것 같습니다.

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/service/AsyncStoageService.js
> +    async function checkIsLoggedIn(setState){
지금은 `isLoggedIn` 만 저장해서 상관없겠지만 이왕이면 함수에 어떤 변수인지도 인자로 넣어주는 편이 더 통합적으로 작성 가능할 것 같아요~!

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/service/TiccleService.js
> +    return {...ticcle, images: imageURLArr};
ticcle 에서 `images` 랑 `imageUrl` 은 다른 것이랍니다.. 노션 참고해주세요
이거 `imageUrl` 이어야 합니다!

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/TiccleDetail.js
> +        if(route.params.screenFrom === 'GroupDetail'){
어디서 TiccleDetail 화면에 왔느냐 가 아니라, TiccleDetail 화면은 자기가 가진 데이터로 동작해야 맞을 것 같아요.
GroupDetail 컴포넌트가 되어있는 형태처럼, props 로 `ticcleData` 를 받아서 처리하는 것이 좋아보여요.
따로 create 에 관한 context 를 재활용하지도 않고요! (create 에는 create 전용이라, 실제 ticcleDate 에 없는 정보들도 있구요)

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/containers/group/detail/components/GroupDetailTiccle.js
> +        navigateTo.navigate('TiccleDetail', {screenFrom : 'GroupDetail'});
이것도 화면 넘겨줄 때 ticcle 에 대한 데이터를 넘겨주는 것이 좋을 것 같아요. (위 comment 와 이어지는 내용입니다.)

+) 이 사안은 "GroupDetail -> TiccleDetail 로 갈 때 params 로 {screenFrom: groupId} 를 줍니다." 에 관련된 내용이 맞나요? groupId 를 준다는 것인가 했는데 "GroupDetail" 이라고 작성되어 있어서 확인차 여쭤봅니다!

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/containers/ticcle/create/TiccleCreate.js
> +            checkScreenFrom(route.params.screenFrom, setTiccleGroup);
여기도 "어디서 왔냐" 보다는 "무엇을 가지고 있냐 (data 관점)" 으로 보는 것이 나중에도 고려할 경우도 줄어들고 깔끔할 것 같아요.
이 화면으로 넘어올 때 props 로 `groupId` 를 넘겨주되, 하단바에서 터치한 경우는 `groupId` 가 비어있을테니 그럼 선택한 그룹 없이 동작하면 되고, 비어있지 않은 경우에는 선택한 그룹이 있다는 것이니 그렇게 동작하도록 하면 될 것 같아요. 어떠신가요?

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/containers/ticcle/create/components/textinput/TiccleContentTextInput.js
> +            onChangeText = {setTiccleContent}
content 내용이 바뀔 따마다 `useTiccleCreate` 의 ticcle content 가 바뀐다면 글 내용이 많아질수록 오버헤드가 상당할 것 같은데 로컬 state 정도로 관리하다가 저장할 때 ticcleCreate 에 반영하는 것은 어떠신가요? 아래 tag 를 처리하신 것처럼요! 지금 건드리기에는 시간이 없을까요

2022-01-21 13:23 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/components/TiccleDetailFloatingButton.js
> +                console.log('delete Ticcle');
실제로 ticcle 삭제하는 부분은 없는 것 맞나요?

2022-01-21 13:35 UTC, never-better commented on src/containers/ticcle/create/TiccleCreate.js
> +            checkScreenFrom(route.params.screenFrom, setTiccleGroup);
지금 코드가 GroupDetail -> TiccleDetail 로 넘어올때는 {screenFrom: groupId} 로 groupId 를 전달해주고 있습니다.  
제가 console로 찍을 때 찍는지 확인하려고 screenFrom이라는 단어를 썼었는데 혼란을 드린 것 같네요. 말하신 것처럼 다 groupId로 이름을 바꾸고 home 에서 올 때는 빈 값을 전달해주겠습니다.

2022-01-21 13:36 UTC, never-better commented on src/containers/group/detail/components/GroupDetailTiccle.js
> +        navigateTo.navigate('TiccleDetail', {screenFrom : 'GroupDetail'});
아이고 잘못 작성했네요 GroupDetail -> TiccleDetail 로 갈 때 groupId를 전달해줍니다.

2022-01-21 13:38 UTC, never-better commented on src/service/AsyncStoageService.js
> +    async function checkIsLoggedIn(setState){
저도 지은님처럼 작성하려고 시도해봤는데 잘 안돼서 일단은 isLoggedIn 만 작성했습니다 ㅎㅎ 우선 순위가 아니니 시간이 남으면 하겠습니다.

2022-01-21 13:41 UTC, never-better commented on src/service/TiccleService.js
> +    return {...ticcle, images: imageURLArr};
이해했습니다. 수정하겠습니다.

2022-01-21 13:44 UTC, never-better commented on src/containers/ticcle/detail/components/TiccleDetailFloatingButton.js
> +                console.log('delete Ticcle');
네. TiccleModel.js의 doDeleteTiccle 함수를 통해 삭제가 되는 것은 확인했습니다. 다만 PR에 작성한 것처럼 티끌 작성 후, TiccleDetail 에서 바로 삭제를 시도하면 오류가 발생해 남겨두었습니다.

2022-01-21 13:45 UTC, never-better commented on src/containers/ticcle/create/components/textinput/TiccleContentTextInput.js
> +            onChangeText = {setTiccleContent}
저도 코드를 작성하다 보니 useTiccleCreate를 사용하기 보다는 TiccleCreate와 TiccleDetail, TiccleEdit 에서 각각 다른 state를 사용하는 것이 낫다는 생각이 들었습니다.  다른 분들 의견을 여쭙고 싶었는데 의견 내주셔서 감사합니다 ㅎ

2022-01-21 13:48 UTC, never-better commented on src/containers/ticcle/detail/TiccleDetail.js
> +        if(route.params.screenFrom === 'GroupDetail'){
context로 그냥 관리하면 더 편할 줄 알았는데 그게 아니네요. 전달해주는 형태로 바꾸겠습니다.

2022-01-21 14:05 UTC, never-better commented
제가 ticcle이 class나 struct처럼 프로퍼티가 고정되어 있다고 착각했습니다. findTiccleById 함수를 수정한 것도 이미지 배열은 하나만 있어야 된다고 착각해서 기존의 image 배열에 imageUrl을 덮어씌워버렸네요.... ㅎㅎ image 배열을 가진 ticcle 하나 imageUrl 배열을 가진 티끌 하나해서 두 개를 관리해야된다고 착각했네요. 객체인데 ㅠㅠ
이걸로 혼자서 고민했는데 진작에 디스코드에라도 올려서 의견을 물어볼 걸 그랬네요. 감사합니다 @0JIEUN0 님!

2022-01-21 15:53 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetail.js
> +    const getTiccleImageFromFirebase = async() => {
이 함수명과 아래 사용된 변수명을 보면  ticcle에 대한 모든 정보가 아닌 ticcle의 image만을 가져오는 것처럼 보입니다. `getTiccleIncludeImages`처럼 명확히 적어주시면 더욱 좋을 것 같습니다. 
ex. `ticcleGetImage`  ->  `ticcleData` 처럼요. 참고로 group 쪽은 `groupData`로 진행했습니다!

2022-01-21 15:58 UTC, bella0413 reviewed
정말 수고하셨습니다! 티끌 기능만 만들어도 힘든데 로그인, 마이페이지 등까지 신경 써주셔서 감사해요👍👍
몇 가지만 말씀드리자면 다음과 같습니다.
- 저도 @0JIEUN0 님 말대로 `context`는 무언가를 생성하는 특정 로직 같은 곳에서만 잠시 사용하고 정보를 보여줄 때는 `model`이나 `props`로 받아야 한다고 생각합니다. 이미 변경하고 계신 걸 알지만 다른 팀원의 의견도 궁금하실까봐 말씀드려요.
- 이것 역시 @0JIEUN0 님과 동일한 의견으로, `screenFrom` 같은 티끌 데이터 외의 `params`를 이용해서 경우를 구분하는 것보다 전달 받은 데이터를 기준으로 구성하는 것이 좋을 것 같습니다. 올려주신 경우 외에도 검색 화면에서 티끌 디테일로 이어지는 경우도 있으니 그 방식이 더 직관적이고 좋을 것 같아요.
- `imageUrl`에 대한 고민, `doUpdateTiccle`은 group 쪽에서 어떻게 처리했는지 참고하시면 도움이 될 것입니다. ticcle과 group 모두 CRUD 기능이 있는 친구들이라 유사한 점이 많아서요. 물론 차이점도 있기에 적절히 반영하시면 될 것 같습니다!
- 티끌 작성과 티끌 수정 페이지 분리 등 수정하신 부분 너무 좋습니다👍Data flow그림을 그려주신 것도 이해하기가 훨씬 쉬워서 좋았어요. 감사합니다. 
- 안 풀리는 부분 있으시면 언제든지 디코에 올려주세요😊화이팅!!

2022-01-24 02:40 UTC, Hongji0611 reviewed
저도 두분의 의견에 동의합니다.  
context 대신 model에서 처리하는 방향이 더 좋을것 같습니다!  
수정 하신 뒤에 다시 의견 남기겠습니다.  
고생하셨습니다👍

2022-01-26 10:40 UTC, 0JIEUN0 requested changes

2022-01-26 10:40 UTC, 0JIEUN0 commented on src/containers/ticcle/create/service/checkGroupId.js
> +            initialTiccle();
"service" 라는 것이 containers 폴더에 들어가는건 현재 저의 프로젝트의 구조와 맞지 않는 것 같습니다.
그리고 이 내용은 TiccleModel 에 들어가면 될 것 같아 보여서요, 의견 주세요!

또 내용이 if else 느낌인데 왜 switch 문을 사용하신 것인지 궁금합니다!

2022-01-26 10:40 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/TiccleDetail.js
> +            <TiccleDetailProvider>
TiccleDetail 을 context 사용하신 이유가 있으실까요?

2022-01-26 10:40 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/components/TiccleDetailInfo.js
> +    const {ticcleDetail} = useTiccleDetail();
이 `ticcleDetail` 을 props 로 받으면 되지 않을까요?

2022-01-26 10:40 UTC, 0JIEUN0 commented on src/context/provider/TiccleUpdateProvider.js
> +        lastModifiedTime: '',
ticcle 자체의 `id` 는 어디에 있나요?!

2022-01-26 13:32 UTC, Hongji0611 commented on src/containers/ticcle/create/TiccleCreateScreen.js
> +    const { ticcle, setTiccle, setTiccleGroup, setTiccleTitle, setTiccleLink,
각화면에 context를 전달해주지 않고, 화면 내에서 불러와도 좋을 것 같습니다!

2022-01-26 13:32 UTC, Hongji0611 commented on src/containers/ticcle/update/components/header/TiccleUpdateHeaderLeft.js
> +                title={"티끌 수정을 취소하시겠습니까?"} leftButton={"취소"} rightButton={"확인"}
디자인, 기획상으로는 없는 모달인 것 같아서요. 한번 의견 여쭤보시는게 좋을 것 같습니다!

2022-01-26 13:32 UTC, Hongji0611 commented on src/containers/ticcle/update/TiccleUpdateScreen.js
> +    const { ticcleUpdate, setTiccleUpdate, setTiccleUpdateGroup,
이부분도 마찬가지로 넘기는 것 보다 각 화면에서 가져오는 게 깔끔할 것 같습니다 (각 화면에서 사용하는 것들로만 정리)

2022-01-26 19:52 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +    const getTiccleImageFromFirebase = async() => {
저번에 말씀드렸던 것과 같은 내용으로, `getTiccleImageFromFirebase`, `ticcleGetImage`는 이미지를 포함한 티끌 데이터와는 다소 거리가 있어 보이니 수정 부탁드립니다.

2022-01-26 19:56 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +    const {ticcleDetail, initialTiccleDetail, setTiccleDetail} = useTiccleDetail()
이 친구들을 꼭 context로 관리해야 하는 이유가 있을까요? state로 관리해도 괜찮을 것 같고 그렇다면 굳이 `initialTiccleDetail`을 하지 않아도 괜찮을 것 같습니다.

2022-01-26 20:00 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +            <TiccleDetailFloatingButton ticcleData={ticcleDetail}/>
왜 이 컴포넌트만 context인 `ticcleDetail`을 props로 전달해주셨는지 궁금합니다.

2022-01-26 20:18 UTC, bella0413 commented
전반적으로 `TiccleUpdateScreen.js` 등 `Screen`이라는 이름을 덧붙여 컴포넌트를 추가하셨는데, 전과 같이 `TiccleUpdate.js` 등의 컴포넌트에 작성해주시면 더욱 좋을 것 같습니다.` Screen`이라는 말 자체도 `navigation`이랑 함께 쓰이는 친구라 헷갈리기도 하고 다른 기능들, 즉 `index.js`역할을 하는 다른 컴포넌트들과의 통일성도 낮아지는 것 같아서요😊

2022-01-27 00:27 UTC, never-better commented on src/containers/ticcle/create/service/checkGroupId.js
> +            initialTiccle();
기존에 화면 3개에서 오는 걸로 함수를 작성했어서 Switch문을 사용했었는데 지금은 필요없어 보이네요. 수정하겠습니다.

2022-01-27 00:34 UTC, never-better commented on src/containers/ticcle/detail/TiccleDetail.js
> +            <TiccleDetailProvider>
가독성과 관리를 위해 사용했습니다.
현재는 TiccleDetail에만 context를 둘러서 사용했기 때문에 전역변수처럼 사용하는 것이 아닌 TiccleDetail 화면에서만 사용하는 것입니다. props와 전달해주는 것과 기능은 똑같지만 가독성이 훨씬 좋습니다. TiccleCreate와  TiccleUpdate의 경우 화면 구성이 거의 동일하기 때문에 컴포넌트 재사용을 했습니다. 그렇기 때문에 props를 사용한 것인데 이 두 파일과 TiccleDetail을 비교해보면 훨씬 읽기 편하고 관리하기 좋습니다.

2022-01-27 00:35 UTC, never-better commented on src/containers/ticcle/detail/components/TiccleDetailInfo.js
> +    const {ticcleDetail} = useTiccleDetail();
위에 답변처럼 코드를 깔끔하게 작성하기 위함입니다.

2022-01-27 00:36 UTC, never-better commented on src/context/provider/TiccleUpdateProvider.js
> +        lastModifiedTime: '',
화면이 렌더링 되면서 ticcleData를 받아와서 업데이트되기 때문에 상관은 없지만 추가하겠습니다.

2022-01-27 00:36 UTC, never-better commented on src/containers/ticcle/create/TiccleCreateScreen.js
> +    const { ticcle, setTiccle, setTiccleGroup, setTiccleTitle, setTiccleLink,
TiccleCreate와 TiccleUpdate의 경우 같은 컴포넌트를 사용해야 해서 가독성은 구리지만 어쩔 수 없이 props를 사용했습니다.

2022-01-27 00:36 UTC, never-better commented on src/containers/ticcle/update/components/header/TiccleUpdateHeaderLeft.js
> +                title={"티끌 수정을 취소하시겠습니까?"} leftButton={"취소"} rightButton={"확인"}
넵 없으면 뭔가 허전해서 추가해놨는데 디자인팀에 물어보겠습니다.

2022-01-27 00:37 UTC, never-better commented on src/containers/ticcle/update/TiccleUpdateScreen.js
> +    const { ticcleUpdate, setTiccleUpdate, setTiccleUpdateGroup,
앞서 말한 것처럼 TiccleCreate의 컴포넌트를 재사용해야되서 어쩔 수 없습니다.

2022-01-27 00:37 UTC, never-better commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +    const getTiccleImageFromFirebase = async() => {
지은님 커밋을 머지 이후에 수정예정입니다.

2022-01-27 00:38 UTC, never-better commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +    const {ticcleDetail, initialTiccleDetail, setTiccleDetail} = useTiccleDetail()
context로 관리하는게 편하고 가독성도 좋습니다. 지은님 코멘트의 답글 확인해주시면 감사하겠습니다.

2022-01-27 00:39 UTC, never-better commented on src/containers/ticcle/detail/TiccleDetailScreen.js
> +            <TiccleDetailFloatingButton ticcleData={ticcleDetail}/>
수정하겠습니다.

2022-01-27 00:47 UTC, never-better commented
> 전반적으로 `TiccleUpdateScreen.js` 등 `Screen`이라는 이름을 덧붙여 컴포넌트를 추가하셨는데, 전과 같이 `TiccleUpdate.js` 등의 컴포넌트에 작성해주시면 더욱 좋을 것 같습니다. `Screen`이라는 말 자체도 `navigation`이랑 함께 쓰이는 친구라 헷갈리기도 하고 다른 기능들, 즉 `index.js`역할을 하는 다른 컴포넌트들과의 통일성도 낮아지는 것 같아서요😊

context를 TiccleUpdate 에서만 사용하는 지역변수로 사용했습니다. context로 감싸지 않고 props로만 전달해주는 것도 생각했으나, contextProvider에 있는 함수 전체(100줄)를 TiccleUpdate.js 에 작성해야 하는데 그러면 코드가 너무 길어집니다. 
contextProvider로 감싼 것일 뿐 기존처럼 navigtae("TiccleUpdate") 를 사용하면 기존과 같이 동작합니다. params를 props를 통해 그대로 전달해주기 때문에 기존처럼 사용하면 됩니다.

2022-01-27 00:57 UTC, 0JIEUN0 commented
저는 TiccleDetail 에서 context 를 사용하신 점에 아직 의문점이 듭니다. context 취지와 기능이 단순 가독성은 아니며 TiccleDetail 의 경우 그 아래 컴포넌트들에 필요한 내용을 전달하는 것으로 오히려 데이터의 흐름을 볼 수 있다고 생각합니다. 무엇보다 지금 TiccleDetail 은 검색 화면에서 진입할 수도 있고, GroupDetail 에서 접근할 수도 있어야 합니다. 그런데 지금처럼 TiccleDetail 에서만 context 를 사용한다면 외부에서 접근이 가능한가요?

2022-01-27 01:07 UTC, never-better commented
> 저는 TiccleDetail 에서 context 를 사용하신 점에 아직 의문점이 듭니다. context 취지와 기능이 단순 가독성은 아니며 TiccleDetail 의 경우 그 아래 컴포넌트들에 필요한 내용을 전달하는 것으로 오히려 데이터의 흐름을 볼 수 있다고 생각합니다. 무엇보다 지금 TiccleDetail 은 검색 화면에서 진입할 수도 있고, GroupDetail 에서 접근할 수도 있어야 합니다. 그런데 지금처럼 TiccleDetail 에서만 context 를 사용한다면 외부에서 접근이 가능한가요?

데이터 흐름을 볼 수 있다는 말에는 동의합니다. 다만 지금처럼 컴포넌트에서 계속 props를 전달해주는 경우 context로 관리하는 경우가 훨씬 편리하다고 생각합니다. context를 사용하면 외부에서 접근이 가능한 건 어떤 걸 말씀하시는 걸까요?

2022-01-27 02:56 UTC, 0JIEUN0 approved these changes
수고하셨습니다!!!!! 👍👍🔥

2022-01-27 03:16 UTC, Hongji0611 approved these changes

2022-01-27 03:59 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetail.js
> +            <TiccleDetailProvider>
> > 전반적으로 `TiccleUpdateScreen.js` 등 `Screen`이라는 이름을 덧붙여 컴포넌트를 추가하셨는데, 전과 같이 `TiccleUpdate.js` 등의 컴포넌트에 작성해주시면 더욱 좋을 것 같습니다. `Screen`이라는 말 자체도 `navigation`이랑 함께 쓰이는 친구라 헷갈리기도 하고 다른 기능들, 즉 `index.js`역할을 하는 다른 컴포넌트들과의 통일성도 낮아지는 것 같아서요😊
> 
> context를 TiccleUpdate 에서만 사용하는 지역변수로 사용했습니다. context로 감싸지 않고 props로만 전달해주는 것도 생각했으나, contextProvider에 있는 함수 전체(100줄)를 TiccleUpdate.js 에 작성해야 하는데 그러면 코드가 너무 길어집니다. contextProvider로 감싼 것일 뿐 기존처럼 navigtae("TiccleUpdate") 를 사용하면 기존과 같이 동작합니다. params를 props를 통해 그대로 전달해주기 때문에 기존처럼 사용하면 됩니다.

앗 `contextProvider` 자체를 `TiccleUpdate.js` 등에 넣어달라는 부탁이 아니었습니다. 단지 `TIccleUpdateScreen.js`와 같은 역할의 컴포넌트들을 말씀드린거예요. 이전과 같이 동일하게 작동하는 점은 좋지만, 통일된 형식 역시 가독성을 높인다고 생각합니다!

2022-01-27 04:10 UTC, bella0413 commented
> > 전반적으로 `TiccleUpdateScreen.js` 등 `Screen`이라는 이름을 덧붙여 컴포넌트를 추가하셨는데, 전과 같이 `TiccleUpdate.js` 등의 컴포넌트에 작성해주시면 더욱 좋을 것 같습니다. `Screen`이라는 말 자체도 `navigation`이랑 함께 쓰이는 친구라 헷갈리기도 하고 다른 기능들, 즉 `index.js`역할을 하는 다른 컴포넌트들과의 통일성도 낮아지는 것 같아서요😊
> 
> context를 TiccleUpdate 에서만 사용하는 지역변수로 사용했습니다. context로 감싸지 않고 props로만 전달해주는 것도 생각했으나, contextProvider에 있는 함수 전체(100줄)를 TiccleUpdate.js 에 작성해야 하는데 그러면 코드가 너무 길어집니다. contextProvider로 감싼 것일 뿐 기존처럼 navigtae("TiccleUpdate") 를 사용하면 기존과 같이 동작합니다. params를 props를 통해 그대로 전달해주기 때문에 기존처럼 사용하면 됩니다.

앗 `contextProvider` 자체를 `TiccleUpdate.js` 등에 넣어달라는 부탁이 아니었습니다. 단지 `TiccleUpdateScreen.js`와 같은 역할의 컴포넌트들을 말씀드린거예요. 이전과 같이 동일하게 작동하는 점은 좋지만, 통일된 형식 역시 가독성을 높인다고 생각합니다!

2022-01-27 04:49 UTC, bella0413 commented on src/containers/ticcle/detail/TiccleDetail.js
> +    const initialTiccleDetail = () => {
`ticcleDetail`을 state로 쓰신다면 `initialTiccleDetail`은 없어도 괜찮습니다.
context와 달리 언마운트되면 다시 초기값으로 재설정되니까요.

2022-01-27 05:02 UTC, merged