Feat/group : 홈, 그룹 디자인 및 로직 추가
WIT-Projects/RTiccle-App pull request #39
Opened 2022-01-24 12:06 UTC by bella0413

## 개요
- 홈, 그룹 디자인 및 로직 추가

## 상세내용
- 홈 화면의 디자인 및 로직이 추가되었습니다.
1. 홈 탭바 디자인 수정.
2.  그룹 생성 갯수 및 최대 갯수를 나타내는 컴포넌트 추가.
3. 신규 티끌 그룹 리스트에서 북마크 이미지 표시.
- 그룹 관련 디자인 및 로직이 추가되었습니다.
1. 그룹 생성에서 `title`중복을 확인. (중복되면 오류 텍스트가 나타남.)
2. 그룹 생성에서 건너뛰기 버튼 관련 로직을 추가. (건너뛰기 버튼을 누르면 이미지 없이 저장, 유저가 이미지를 추가하면 건너뛰기 버튼이 사라짐.)
## 리뷰어가 확인할 사항
- 디자인 수정 사항 중 디자이너님께 확인받아야 하는 부분은 아직 수정하지 않았습니다. (그룹 업데이트에서 `title` 중복 확인 등)

## 기타
- @0JIEUN0 감사합니다...감사합니다....

2022-01-24 14:25 UTC, 0JIEUN0 requested changes

2022-01-24 14:25 UTC, 0JIEUN0 commented on src/containers/group/create/components/GroupTitleInput.js
> +const TitleInput = ({setButtonDisable, isExistGroup}) => {
혹시 요거 컴포넌트 이름 `GroupTitleInput` 아닌가요?!

2022-01-24 14:25 UTC, 0JIEUN0 commented on src/containers/group/create/components/GroupTitleInput.js
> +                <Text style={styles.textCount}>{groupTitleLength}/15</Text>
여기 15도 `maxLengthOfTitle` 사용하시면 좋을 것 같아요!

2022-01-24 14:25 UTC, 0JIEUN0 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
이거 저도 그렇고 `main` 브랜치도 그렇고 파일 자체가 groupInfo.js 랑 zeroTiccle.js 로 되어있는데 오류나지 않나요..??

2022-01-24 14:49 UTC, Hongji0611 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
저도 그래서 저번 PR에 파일명 바꿔놨는데 깃에는 반영이 안되더라고요...?

2022-01-24 14:49 UTC, Hongji0611 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
저도 그래서 저번 PR에 파일명 바꿔놨는데 깃에는 반영이 안되더라고요...?

2022-01-24 14:50 UTC, Hongji0611 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
저도 그래서 저번 PR에 파일명 바꿔놨는데 깃에는 반영이 안되더라고요...?

2022-01-24 16:02 UTC, bella0413 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
저도 저번 PR에 파일명 바꿔놨는데 깃에 반영이 안되더라구요...?

2022-01-24 16:12 UTC, bella0413 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
https://docs.github.com/en/repositories/working-with-files/managing-files/renaming-a-file
정 안되면 이런 식으로 바꿔도 될 것 같아요

2022-01-25 00:40 UTC, 0JIEUN0 commented on src/containers/group/detail/GroupDetail.js
> +import ZeroTiccle from './components/ZeroTiccle';
아하 그냥 반영이 안된 것이군요
저는 로컬에서도 파일이름이 저래서 제가 바꿔서 올렸습니다!!

2022-01-25 00:40 UTC, 0JIEUN0 approved these changes

2022-01-25 11:25 UTC, Hongji0611 approved these changes

2022-01-26 04:53 UTC, never-better commented
Let's Merge

2022-01-26 05:21 UTC, merged