Local search
WIT-Projects/RTiccle-App pull request #46
Opened 2022-01-28 15:04 UTC by Hongji0611

## 개요
- 그룹 상세화면에서 티끌 검색

## 상세내용
- 그룹 상세화면에서 로컬 정보(ticcleList)를 바탕으로 검색을 할 수 있습니다.
- 모든 쿼리는 제목+태그 검색이 가능 / '#'이 붙은 태그쿼리는 태그만을 검색합니다.
- x버튼을 누르면 기존 티끌리스트가 보여집니다.

## 리뷰어가 확인할 사항
- `react-native-reanimated` 패키지가 일정 버전 이상에서 사용이 불가능하다고 하여 삭제했습니다. (다른 곳에서도 사용되지 않는 패키지임을 확인했습니다.)
- 검색화면에서도 groupDetail 화면에 접근해야하는 상황이 발생하는데, 이때는 티끌 정보가 ticcleList에 존재하지 않아서 파라미터로 ticcleData를 넘길 수 없게 됩니다. 그래서 검색화면에서 데이터가 넘어오는 경우 groupDetail의 파라미터를 ticcleId로 설정하고,  서버에서 가져오는 형식을 추가하는 것이 어떨까 @never-better님과 다른 팀원분들께 의견을 묻고 싶습니다!

## 기타
- groupDetail의 파라미터가 정해진 뒤, algolia 검색 관련 새로운 PR 올리겠습니다!

2022-01-29 01:10 UTC, 0JIEUN0 requested changes
오류나는 패키지... 찾아내주셔서 감사합니다ㅜ!
ticcle 정보를 가져오는 것에 대한 의견은 아래 comment 참고해주세요!

2022-01-29 01:10 UTC, 0JIEUN0 commented on src/containers/search/components/SearchExistResult.js
>      function getTitle() {
요게 결국 getGroupTitle 인거죠?? ticcle 이랑 혼동되니 수정 부탁드려도 될까요?

2022-01-29 01:10 UTC, 0JIEUN0 commented on src/containers/search/components/SearchExistResult.js
> +    function getTiccle(){
저는 TiccleDetail 에서 ticcle id 에 대한 ticcle 정보를 받아오는 것이 아닌,
이 SearchExistResult 에서 선택한 티끌의 경우 getTiccle 로 정보를 받아오는 것의 형식으로 통일하면 좋을 것 같아요.
즉, 여기서 ticcle id 에 대해 해당 정보를 받아와서 TiccleDetail 에 넘겨주면 될 것 같아요!

그리고 다른 분들이 혼동스러우실 수 있으실텐데, local search 는 ticcle list 가 있는 상황, 즉 GroupDetail 에서 검색을 하는 경우이고 전체 검색은 아예 검색 화면에서 모든 Ticcle 을 대상으로 검색하는 것입니다! 
그래서 지우님이 말씀하신 
> 티끌 정보가 ticcleList에 존재하지 않아서 파라미터로 ticcleData를 넘길 수 없게 됩니다

가 전체 검색에 해당하는 것으로 전 이해했습니다. 맞을까요??

2022-01-29 01:10 UTC, 0JIEUN0 commented on src/service/SearchService.js
> +    const uniqueArr = [...set];
와 대박

2022-01-29 01:40 UTC, bella0413 reviewed
저도 @0JIEUN0 님 말씀대로 특정 `SearchExistResult`가 선택되면 해당 ticcle에 대한 모든 정보를 받아오고, 그것과 함께 `navigate`하는 게 좋을 것 같습니다. 현재 구현된 `TiccleDetail`도 어디에서 오든 상관없이 `ticcleData`를 받아서 보여준다는 느낌으로 논의되었어서요. 
그리고 기타 사항에 groupDetail말고 ticcleDetail 말씀하신 건가요...??

2022-01-29 07:10 UTC, never-better commented on src/containers/common/SearchBar.js
> +    const pressDeleteSearchBtn = (e) => {
e 가 필요없어 보입니다.

2022-01-29 13:15 UTC, Hongji0611 commented on src/containers/search/components/SearchExistResult.js
> +    function getTiccle(){
넵! ticcle정보를 서버에서 받아서 TiccleDetail에 넘기도록 반영했습니다. (전체 검색에 해당하는 내용 맞습니다~!)

2022-01-29 13:16 UTC, Hongji0611 commented
팀원분들의 의견에 맞춰 전체 검색인 경우 SearchExistResult에서 ticcle id로 ticcle을 받아 넘기는 방식으로 수정했습니다~!

2022-01-29 15:35 UTC, bella0413 approved these changes
LGTM😊👍👍

2022-01-30 01:56 UTC, 0JIEUN0 approved these changes
수고하셨습니다 😀👍

2022-01-30 03:30 UTC, never-better approved these changes

2022-01-30 14:03 UTC, merged