Feat/my page&ticcle limit
WIT-Projects/RTiccle-App pull request #50
Opened 2022-01-31 07:00 UTC by never-better

## 개요
마이페이지 수정 및 모달

## 상세내용
마이페이지를 디자인에 맞게 수정했습니다.
- 개인정보처리방침 모달
- 데이터 초기화
- 로그아웃

티끌 최대 생성시 모달창이 뜹니다.

TiccleUpdate에서 orginal이 참조되던 현상을 끊어주었습니다. (지은님 짱, 지우님, 윤전님도 짱)

티끌 생성 후 GroupDetail 페이지에 업데이트가 안 되는 것을 수정해주었습니다.
근데 이게 됐다가 안 됐다가 해서 조금 더 확인이 필요합니다. 

Modal 애니메이션 fadeIn/Out으로 통일

## 리뷰어가 확인할 사항
react-native-restart 패키지 설치했습니다. 확인해주세요.

## 기타
지금은 로그아웃 후에 마이페이지에서 guest 유/무만 바뀌도록 설정했습니다.

2022-01-31 08:23 UTC, 0JIEUN0 requested changes

2022-01-31 08:23 UTC, 0JIEUN0 commented on src/containers/group/detail/components/GroupDetailFloatingButton.js
> +        if(ticcleNum > 100) {
ticcle 개수 제한에 대해서는 `GroupModel` 에 `limitTiccleNum` 와 `getTotalTiccleNum` 을 만들어두었습니다.
해당 내용을 올릴 때 말씀드린 것처럼, 이를 사용하시길 바랍니다! (그냥 100 이 아닌,  `limitTiccleNum` 사용)

그리고 지금 `ticcleNum > 100` 라고 작성해주셨는데, 그러면 `ticcleNum` 이 100 인 경우에도 티끌 생성이 가능한 로직 아닌가요?

2022-01-31 08:23 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/components/header/TiccleDetailHeaderLeft.js
> +                setIsGroupChanged(!isGroupChanged);
TiccleDetail 에서 left 버튼(백버튼)을 누를 떈 group 정보는 바뀌는 것이 없지 않나요?

2022-01-31 08:23 UTC, 0JIEUN0 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
로그아웃 후 앱 재시작으로 하지 않으신 이유가 혹시 무엇인가요?
restart 부분이 안되어있나 했는데, 데이터 초기화에서는 restart 를 하셔서요.

2022-01-31 08:23 UTC, 0JIEUN0 commented on src/navigation/MainTab.js
> +                title={"티끌은 100개까지 생성 가능합니다."} rightButton={"확인"}
여기도 100 을 하드코딩으로 넣지 않고 `limitTiccleNum` 을 사용해주시면 좋을 것 같아요~!

2022-01-31 09:17 UTC, never-better commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
다른 분들 의견 물어보고 진행하려고 우선 냅뒀습니다.

2022-01-31 09:19 UTC, never-better commented on src/containers/ticcle/detail/components/header/TiccleDetailHeaderLeft.js
> +                setIsGroupChanged(!isGroupChanged);
group의 latestTiccleTitle이 바뀌어서 사용했습니다. (홈 화면에서 그룹의 최신 띠끌을 위해서)
근데 업데이트가 안되고 앱 재실행해야 업데이트 되네요...

2022-01-31 09:21 UTC, never-better commented on src/containers/group/detail/components/GroupDetailFloatingButton.js
> +        if(ticcleNum > 100) {
아 이거 지은님이 getTotalTiccleNum 수정하기 전에 작업한거라 브렌치 합치고 작업하려고 아껴뒀습니다. ㅎㅎ
부호는 >= 가 맞겠네요!

2022-01-31 09:30 UTC, Hongji0611 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
로그아웃 이후 재시작하면,
게스트로 로그인해도 구글연동이 되어있나요?

2022-01-31 10:14 UTC, never-better commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
로그아웃을 하면 바로 로그아웃이 되기 때문에 게스트로 로그인하면 구글연동은 되지 않습니다. 게스트로 로그인하기 때문에 새로운 계정이 생깁니다.

2022-01-31 10:17 UTC, bella0413 commented on package.json
> +    "react-native-restart": "^0.0.23",
?? 저번 제 에러 핸들링 PR에서 `react-error-boundary` 패키지 이미 추가했는데 왜 @never-better 님 코드에는 없죠..??
에러 핸들링 PR에서 추가한 `react-error-boundary`도 없는 걸 봐서 pull이 덜 되신 것 같습니다.

2022-01-31 10:17 UTC, 0JIEUN0 commented on src/containers/ticcle/detail/components/header/TiccleDetailHeaderLeft.js
> +                setIsGroupChanged(!isGroupChanged);
오잉 그거는 티끌 생성 혹은 수정 시 바꿔주니 상관없지 않나요? 조회한 최신 티끌이 아니니깐요!

2022-01-31 10:19 UTC, 0JIEUN0 commented on package.json
> +    "react-native-restart": "^0.0.23",
그 사이에 작업하신 것 같아요 그래도 말씀하신 것처럼 main 이 업데이트되면 pull 이나 rebase 등으로 최신 버전을 가져와서 올려주시면 좋을 것 같아요.

2022-01-31 10:20 UTC, never-better commented on package.json
> +    "react-native-restart": "^0.0.23",
그 전에 작업했어요. rebase로 가져오고 코멘트 남겨주신 사항들 수정하겠습니다.

2022-01-31 10:24 UTC, 0JIEUN0 commented on package.json
> +    "react-native-restart": "^0.0.23",
지금은 그냥 이렇게 작업해도 될 것 같아요! 이미 올려둔거니 여기서 작업하시고 충돌만 해결하시면 되리라 생각합니다.

2022-01-31 10:32 UTC, never-better commented on package.json
> +    "react-native-restart": "^0.0.23",
그냥 rebase해서 지은님이 작성하신 getTiccleNum 함수까지 적용하는 게 나을 것 같아요. ㅎㅎ

2022-01-31 10:34 UTC, bella0413 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
기획자님께도 물어볼까요...???

2022-01-31 10:36 UTC, Hongji0611 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
네!!!

2022-01-31 10:37 UTC, never-better commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
재시작이 맞는 거 같긴 합니다. 지금 짠 코드로는 로그아웃하고 재시작을 안 하면 유저 id가 없어서  글을 작성할 수가 없어요.

2022-01-31 10:39 UTC, never-better commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
혹시나 다른 의견있을까봐 안 정한건데 개발팀에서 정할 수 있으면 재시작으로 갈까요?

2022-01-31 10:42 UTC, Hongji0611 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
재시작에 동의합니다!

2022-01-31 10:52 UTC, bella0413 commented on src/containers/user/components/Settings.js
> +        setIsGuest(true);
저도 좋아요~~

2022-01-31 11:17 UTC, bella0413 commented on src/navigation/MainTab.js
> +                            if(ticcleNum > 100) {
여기도 비교연산자 수정 부탁드려요

2022-01-31 11:19 UTC, never-better commented on src/containers/ticcle/detail/components/header/TiccleDetailHeaderLeft.js
> +                setIsGroupChanged(!isGroupChanged);
고럼 지우겠습니다

2022-01-31 11:19 UTC, never-better commented on src/navigation/MainTab.js
> +                            if(ticcleNum > 100) {
지은님이 만든 함수 있어서 다 통일했습니다~

2022-01-31 11:24 UTC, bella0413 approved these changes

2022-01-31 11:46 UTC, Hongji0611 approved these changes

2022-02-01 01:26 UTC, 0JIEUN0 approved these changes

2022-02-01 01:26 UTC, merged