Feat/group
WIT-Projects/RTiccle-App pull request #7
Opened 2021-11-17 17:16 UTC by bella0413

## 개요
- 전반적인 네비게이터 정리 및 그룹 헤더 이미지 추가 화면 생성

## 작업내용
- App.js에 BottomTabNavigator를 가장 상위 네비게이터로 만들었습니다.
- 그룹 헤더 이미지 추가 화면을 외부 라이브러리를 활용하여 만들었습니다.
- PR 양식을 만들었습니다.

## 리뷰어가 확인할 사항
- 패키지가 추가되었으니 다들 반영하고 실행해주세요!

## 기타
-

2021-11-19 09:25 UTC, Hongji0611 commented on src/containers/group/create/GroupCreate.js
> +      <GroupCreateHeaderImage></GroupCreateHeaderImage>
컴포넌트를 나누면 좋을 것 같아요 (예를 들면 모달, 이미지 뷰어, 버튼)

2021-11-19 09:25 UTC, Hongji0611 commented on src/containers/group/create/components/GroupCreateHeaderImage.js
> +            width: 412,
width를 100% 혹은 windowsWidth이 좋을 것 같습니다!

2021-11-19 09:28 UTC, Hongji0611 requested changes
고생하셨습니다👍👍

2021-11-19 09:31 UTC, Hongji0611 approved these changes

2021-11-25 07:51 UTC, never-better approved these changes
😁

2021-11-25 07:51 UTC, merged

2021-11-25 13:52 UTC, bella0413 reviewed
ㅋㅋㅋㅋ 재빠른 머지로 인해 다음 PR에 말씀하신 부분을 반영하겠습니다