Home
WIT-Projects/RTiccle-App pull request #8
Opened 2021-11-26 07:32 UTC by Hongji0611

## 개요
- HomeScreen
- Home에서 그룹 클릭 시 그룹 상세화면으로 이동

## 상세내용
- Home에서 산 부분(MyMount.js), 바로가기 부분(BookMarkList.js), 최근 티끌 생성 그룹 부분(NewTiccleGroupList.js)으로 나누어 작성했습니다.
- 티끌 바로가기(MarkTiccle.js)와 그룹 바로가기(TiccleGroup.js)는 컴포넌트로 분류했습니다.
- 그룹바로가기에서 그라데이션.png 파일을 이미지위에 덮어씌워 처리했습니다.
- 네비게이션의 큰 틀은 Tab이며 HomeStack을 두어 화면 전환을 했습니다.

## 리뷰어가 확인할 사항
- npm native-stack을 진행했으니 패키지 모듈 확인해주세요!

## 기타
- 이미지(아이콘) 컴포넌트는 아직 적용하지 않았습니다. 추후에 바뀌면 수정하겠습니다.

2021-11-26 13:43 UTC, 0JIEUN0 requested changes
EOF 만 체크해주시면 될 것 같습니다~!

2021-11-26 13:43 UTC, 0JIEUN0 commented on src/containers/home/index.js
> +        <BookMarkList userName={"김민지"}></BookMarkList>
UserName 을 출력하는 것이 적절한지 검토 필요
(현재로서는 게스트일 경우 "게스트"님, 구글 로그인 유저인 경우 이메일이 보여지게 됨)

2021-11-26 13:43 UTC, 0JIEUN0 commented on src/containers/home/components/MyMount.js
> +export default MyMount;
EOF 확인 부탁드려요!

2021-11-29 11:06 UTC, Hongji0611 commented on src/containers/home/components/MyMount.js
> +export default MyMount;
EOF되어있습니다!! EOF이 없으면 동그라미에 마이너스 있는 게 빨간색으로 뜹니다~!

2021-11-29 11:10 UTC, bella0413 commented
`@react-navigation/stack` 대신 `native-stack`을 쓰는 이유가 무엇인가요? stack이 더 커스텀하기 쉽다고 알고 있어서요!

2021-11-29 11:12 UTC, 0JIEUN0 commented on src/containers/home/components/MyMount.js
> +export default MyMount;
아 그렇군요!!!!

2021-11-29 11:13 UTC, 0JIEUN0 approved these changes

2021-11-29 11:17 UTC, never-better approved these changes

2021-11-29 11:23 UTC, Hongji0611 commented
오호 stack이 더 커스텀하기 쉽군요!! 하나 더 깨달았습니다

2021-11-29 11:55 UTC, merged